name: arup_util
description: Collection of Widgets and helpful Methods that every developer needs.
version: 0.0.1
homepage: https://github.com/arupnaskarbkp/arup_util.git

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
